### ISSUE TITLE
bug in get_geneID_symbol()

### ISSUE THREAD

**Issue by hukai916** [haibol2016/ArchR_utilities#4]
In line 110, 
```
id_symbol <- data.frame(gene_id = gene_id, symbol = gene_id)
```
should be
```
id_symbol <- data.frame(gene_id = unlist(id2symbol_dict$keys()), symbol = unlist(id2symbol_dict$values()))
```

**Comment by haibol2016** [comment]
@hukai916 , I have  `gene_id = unlist(id2symbol_dict$keys())` a few lines above. So I prefer 
` id_symbol <- data.frame(gene_id = gene_ids, symbol = gene_ids)` 

Sorry I had a typo before. gene_id should be "gene_ids"
